### ISSUE TITLE
Getting 401 from API -> `oauth/v2/token` 

### ISSUE THREAD

**Issue by salaboy** [zitadel/react-user-authentication#2]
Hi folks, 
I am trying to run this example app against Zitadel Cloud, but after login, I am getting 401 in the `oauth/v2/token`  of my instance. 
It would be really helpful if the `README.md` describe how we need to configure our application inside Zitadel Cloud to ensure that it has all the rights to access all the URLs required by this app. 

I am also facing issues with enabling the self-registration form, can you please advice? I don't seem to be able to make that appear when I go to the login form for the application.

**Comment by dakshitha** [comment]
Hey! Yes, the readme has to be updated. Thanks for the reminder :)

But all the instructions related to this example can be found here - https://zitadel.com/docs/guides/start/quickstart
Did you already see that?

**Comment by salaboy** [comment]
A link in the readme to those steps will be highly appreciated.. I haven't seen that before

**Comment by salaboy** [comment]
ok with PCKE the 401 is gone :)

**Comment by dakshitha** [comment]
Yes, I added it. Thanks for pointing it out. 

Glad it's working for you :)
